### ISSUE TITLE
compatible bug with pywinauto

### ISSUE THREAD

**Issue by wangtubs** [glitchassassin/lackey#65] opened 2017-03-05 14:08 UTC
Hi, I use lackey together with pywinauto form GUI automation on windows. when I import lackey and use pywinauto to fill in forms, it gives error 
```
    itunes2.child_window(control_type="Edit",found_index=0).type_keys(self.email)
  File "C:\Python27\lib\site-packages\pywinauto\base_wrapper.py", line 832, in type_keys
    turn_off_numlock)
  File "C:\Python27\lib\site-packages\pywinauto\keyboard.py", line 634, in SendKeys
    k.run()
  File "C:\Python27\lib\site-packages\pywinauto\keyboard.py", line 364, in run
    ctypes.sizeof(win32structures.INPUT))
ctypes.ArgumentError: argument 2: <type 'exceptions.TypeError'>: expected LP_INPUT instance instead of pointer to INPUT_Array_2
```
if I don't import lackey, it works fine. is it a bug from ctypes or keyboard? how to fix it?
thanks

**Comment by glitchassassin** [comment] 2017-03-06 15:32
How strange. I'm not immediately sure what's causing this.

What version of Windows are you on? Are you running Python 64bit or 32bit?

**Comment by glitchassassin** [comment] 2017-03-06 15:47
Also, are you importing lackey first in your script or pywinauto? Does it make a difference if you flip the imports around?

**Comment by wangtubs** [comment] 2017-03-06 17:41
I use windows 8 R2, python 32 bit. Now is fine after I reinstall pywinauto. Now I meet another problem, in the last step on itunes, I use lackey to click the menu, the mouse moves very slow. while on other steps it reacts quite fast. I don't know what's the problem.

**Comment by glitchassassin** [comment] 2017-03-07 13:52
The mouse move is supposed to happen in a constant amount of time (by default 0.3 seconds) regardless of the distance. This results in long mouse moves happening apparently faster than slow ones, even though they take the same amount of absolute time.

Could this be your problem?

(Note that I did discover an issue yesterday where Settings.MoveMouseDelay was not being respected after it was updated - this should be fixed in the development ring, and will be pushed out with the next version.)

**Comment by wangtubs** [comment] 2017-03-07 14:02
the mouse actually is at the bottom of the window, I could see that mouse moves slowly to the menu. there should be another click event on the submenu, but often failed because of the slow click event on the menu. I even suppose itunes make the system slower after activating the itunes account, because we I use pywinauto before, it is also very slow(wait ~80s)

**Comment by glitchassassin** [comment] 2017-03-07 14:29
Is the system less responsive when you move the mouse manually as well at this point, or do you only observe this with simulated mouse movements? Is Sikuli affected, or only pywinauto/lackey?

**Comment by wangtubs** [comment] 2017-03-08 16:36
when I manually move the mouse, it moves quite fast. currently I find both pywinauto/lackey are affected. I didn't try sikuli because I don't Jython

**Comment by wangtubs** [comment] 2017-03-08 21:00
it is so strange. today I try to use hotkey to get the submenu after activate the itunes with lackey. before activating, the hotkey works fine, after activating not working anymore. so strange.

**Comment by wangtubs** [comment] 2017-03-08 21:11
here is the error for the slow click event
```
[info] Found match for pattern 'C:\Users\Administrator\Desktop\itunes\img/account.png' at (228,77) with confidence (0.977361857891). Target at (257,90)
[action] Clicked at (Location object at (257,90))
[info] Couldn't find 'C:\Users\Administrator\Desktop\itunes\img/menu_signout.png' with enough similarity.

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Python27\lib\site-packages\keyboard\_generic.py", line 59, in process
    if self.pre_process_event(event):
  File "C:\Python27\lib\site-packages\keyboard\__init__.py", line 117, in pre_process_event
    event.scan_code = to_scan_code(event.name)
  File "C:\Python27\lib\site-packages\keyboard\__init__.py", line 577, in to_scan_code
    scan_code, modifiers = _os_keyboard.map_char(_normalize_name(key))
  File "C:\Python27\lib\site-packages\keyboard\_winkeyboard.py", line 447, in map_char
    raise ValueError('Key name {} is not mapped to any known key.'.format(repr(name)))
ValueError: Key name 'left alt' is not mapped to any known key.
```

**Comment by wangtubs** [comment] 2017-03-09 11:53
hi, not only the mouse move slow, the exits methods is also slow in this window. 
```
if lackey.exists('img/success.png',seconds=30):
    print 'success'
```
it sometimes takes quite long for image recognition. sometime over 30s.

**Comment by wangtubs** [comment] 2017-03-09 11:54
oh, maybe it is the problem of pywinauto. I use pywinauto to close the client. it often throw an error.

**Comment by glitchassassin** [comment] 2017-03-15 17:43
It could be the combination of pywinauto and Lackey, I'm not sure. Both access low-level Windows routines, so they might be stepping on each others' toes, so to speak.

That ValueError is perplexing to me. It looks like a bug with keyboard, but I'm not sure where. Can you post the section of your code that causes this error?

**Comment by glitchassassin** [comment] 2017-04-10 12:49
Closing as not reproducible.

**Closed by glitchassassin** 2017-04-10 12:49 UTC
