### ISSUE TITLE
Windows 10 Installation Dialog Interaction Problem

### ISSUE THREAD

**Issue by maxdule** [glitchassassin/lackey#49] opened 2017-01-16 10:49 UTC
Lackey is having issue interacting with Windows 10 installation dialogues (created with NSIS installer). It does see a button, seems like it simulates a click but nothing happens. Log states that click was performed on desired location.

Focusing application does not seem to work either, as if no interaction is possible.

NOTE: Sikuli has same problem on Windows 10.
NOTE: Same code runs on a Windows 7 machine without problem.

Do you maybe know what could be the problem, and if there is a workaround?

**Comment by glitchassassin** [comment] 2017-01-16 16:19
1. Does the installer run full-screen or windowed?
2. Is the un-clickable button on a modal window like a "needs administrator permissions" dialog?
3. Does the installation dialog accept keyboard input?

**Comment by maxdule** [comment] 2017-01-16 18:53
1. Windowed
2. Installer only checks if user is running it under administration privileges (before started). I've additionally tried with random installer from web, and it didn't work either. And it's not just the button, neither focus (on this window) nor simply clicking on the text (to make it focused) work.
3. It does, but hovering the button and typing "Enter", for instance, doesn't work either.

**Comment by glitchassassin** [comment] 2017-01-16 19:45
Thanks. Last question - did you notice if this ever worked in the past?

**Comment by maxdule** [comment] 2017-01-16 21:41
Unfortunately not. However, I could test it with specific (previous) version if this could help.

**Comment by glitchassassin** [comment] 2017-01-16 23:15
In version 0.5.0 I replaced the existing low-level mouse/keyboard automation with the `keyboard` library. You might try it with v0.4.2a1 (the prior release) to see if it works with the original code.

I'll see if I can reproduce the issue on my Windows 10 laptop as well.

**Comment by glitchassassin** [comment] 2017-01-17 00:16
I have successfully duplicated this issue with Sikuli 1.1.0 and the XAMPP installer (which I believe uses NSIS).

No simulated keyboard or mouse events (including moving the mouse, clicking mouse buttons, or typing the Enter key) are triggered while the installer is the foreground window. These events function normally when an actual keyboard or mouse is used. If a different window is the foreground window, the mouse can move over the installer, but the installer doesn't receive the click or move to the foreground.

If Sikuli is launched as an administrator, however, the keyboard & mouse events are triggered just fine.

This may be a fixable access issue, so I'll investigate further. But the workaround may end up being "run your script as administrator."

**Comment by glitchassassin** [comment] 2017-01-17 00:32
It looks like a non-elevated script [can't automate an application running with elevated privileges](http://stackoverflow.com/questions/31627385/activate-windows-alt-tab-switcher-with-sendinput) (which makes sense when you think about it).

Sikuli gives a warning when it detects that the mouse failed to respond. I'll look into adding this into Lackey, and will certainly add it to the documentation.

**Comment by maxdule** [comment] 2017-01-17 10:22
You are absolutely right. I've been aware of the Sikuli behavior, but I've managed to pass around with Lackey as well - by running code with Jenkins both server and node in admin mode. In this case interaction works.

Thanks for the quick responses, as far as I'm concerned this issue can safely be closed, with docs updated.

Cheers!

**Comment by glitchassassin** [comment] 2017-01-17 14:50
Sounds good. I've pushed an updated README and added a helpful exception if Lackey detects that its mouse messages are being ignored. These will be rolled out with the next release.

**Comment by glitchassassin** [comment] 2017-01-17 16:27
This has been fixed in the latest release.

**Closed by glitchassassin** 2017-01-17 16:27 UTC
Labels: fix in testing
