### ISSUE TITLE
launch application error with lackey

### ISSUE THREAD

**Issue by wangtubs** [glitchassassin/lackey#67] opened 2017-03-09 12:30 UTC
I try to launch iTunes with lackey. 
```
import lackey
app = lackey.App("C:\\Program Files\\iTunes\\iTunes.exe").open()
```
nothing happens.
when I test with app = lackey.App("notepad.exe").open()
the notepad is opened. I change to
app = lackey.App("iTunes.exe").open()
also nothing happens

**Comment by wangtubs** [comment] 2017-03-09 12:49
I solved by using app = lackey.App(r'"C:\\Program Files\\iTunes\\iTunes.exe"').open()

**Comment by glitchassassin** [comment] 2017-03-09 14:51
That's the correct answer. Lackey will treat the string as a single command, so if there are spaces, the path has to be enclosed in quotes *within* the string to make sure the operating system recognizes it as a single token:

    [C:\Program] [Files\iTunes\iTunes.exe]

vs

    ["C:\Program Files\iTunes\iTunes.exe"]

This looks like it's operating as designed. Unless you have any concerns, I think we can close out this issue?

**Comment by wangtubs** [comment] 2017-03-09 14:57
ok. you can close. A small issue is that when i use app.close() to kill the app, it outputs some error information from the client. but the client can be closed without problem. can you remove this error information?

**Comment by glitchassassin** [comment] 2017-03-09 15:21
Can you post a sample?

**Comment by wangtubs** [comment] 2017-03-09 15:53
```
Child read:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AMSMessageSignatureKey</key>
	<array>
		<string>AMSNotificationPipeNameKey</string>
	</array>
	<key>AMSNotificationPipeNameKey</key>
	<string>\\.\pipe\30578924-576340073114863428</string>
	<key>AMSRequestKey</key>
	<string>AMSSetUpNotificationPipeRequest</string>
</dict>
</plist>

Child sending:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict/>
</plist>

Child: Can't read length for data, error code 109
```

**Comment by wangtubs** [comment] 2017-03-10 18:22
I think sometimes lackey can't close the itunes properly.

**Comment by glitchassassin** [comment] 2017-03-16 13:14
After a bit of research, I think I've figured out how to muffle these errors. Doing a bit more testing to make sure it doesn't break anything. I've committed a fix to the develop ring and will roll it out to production when it's ready.

**Comment by jazz1215** [comment] 2017-03-17 01:13
For launching application this will work:
app = lackey.App("\"C:\\Program Files\\iTunes\\iTunes.exe\"").open()

**Comment by glitchassassin** [comment] 2017-03-17 11:43
It will if you replace those outer quotes with single quotes. =)

**Comment by glitchassassin** [comment] 2017-03-21 12:44
This fix has been rolled out to Pypi.

**Closed by glitchassassin** 2017-03-21 12:44 UTC
Labels: enhancement, fix in testing
