### ISSUE TITLE
can you giving a demo?

### ISSUE THREAD

**Issue by 23233** [glitchassassin/lackey#44] opened 2017-01-02 03:30 UTC
I've had enough of sikilix to rely on, but I do not know how to use this framework?

**Comment by glitchassassin** [comment] 2017-01-03 15:17
Hi,

If you've used SikuliX, then it's easy to convert one of your SikuliX projects to pure Python.

I'll assume that you have Python already installed and followed the instructions in the README to install Lackey via `pip`. If not, [start there](https://github.com/glitchassassin/lackey).

Then, just add the following line to the top of your SikuliX script:

    from lackey import *

Now you can call the Python script in your SikuliX project directly, e.g.:

    python MySikuliProject.sikuli/MySikuliProject.py

If you want to be able to run it from SikuliX again, you can either comment out the `lackey` import or use a try/except to catch and ignore the exception:

    try:
        from lackey import *
    except:
        # Running from within Sikuli IDE
        pass

(The try/except is better because you can run either from inside the IDE or from Python via Lackey without editing your code.)

I find this workflow - developing in the Sikuli IDE and then running via Lackey - works best for me. But if you want to write directly in Python, you can refer to [the documentation for SikuliX](http://sikulix-2014.readthedocs.io/en/latest/). The syntax will be the same, you just won't have all the helpful tools that the IDE provides.

**Caveats**

SikuliX has a couple advanced features that haven't been implemented yet in Lackey - specifically, OCR and event handling. If your script relies on those features, you'll need to run it through Sikuli until they're implemented in a future release of Lackey.

Lackey is currently Windows-only, though I eventually plan to include Linux support.

Does this help?

**Comment by glitchassassin** [comment] 2017-01-05 17:18
I was able to reproduce the issue with Python 3.5.2. I've pushed a fix to the `develop` ring. I'll do some further testing and then roll it out in a bit.

Thanks for the report!

**Comment by jazz1215** [comment] 2017-01-11 04:12
Is there any chance that this issue relates to 32bit or 64bit Python?

I have 2 PCs, one with 32bit Python 2.7.12 and the other with 64bit Python 2.7.12 installed.  Both have latest 0.5.2 Lackey installed with pip.

On the machine with 32bit, a failed Find will raise FindFailed exception, which is good.  However, on the machine with 64bit Python, a "WIndowsError: exception access violation reading 0x0000000C00000000" will be raised.   Please see below for details:

**32Bit Python:**
Python Version:
2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]

Error:
`[info] Couldn't find 'c:\testimage.png' with enough similarity.
Traceback (most recent call last):
  File "C:\guitest.py", line 11, in <module>
    print find(r'c:\testimage.png')
  File "C:\Python27\lib\site-packages\lackey\RegionMatching.py", line 386, in find
    raise FindFailed("Could not find pattern '{}'".format(path))
lackey.Exceptions.FindFailed: Could not find pattern 'c:\testimage.png'
`

**64Bit Python**
Python Version:
2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]

Exception:
`Traceback (most recent call last):
  File "E:\guitest.py", line 11, in <module>
    print find(r'E:\testimage.png')
  File "E:\3rdParty\Python-2.7.12\lib\site-packages\lackey\RegionMatching.py", line 383, in find
    match = self.exists(pattern)
  File "E:\3rdParty\Python-2.7.12\lib\site-packages\lackey\RegionMatching.py", line 528, in exists
    matcher = TemplateMatcher(r.getBitmap())
  File "E:\3rdParty\Python-2.7.12\lib\site-packages\lackey\RegionMatching.py", line 349, in getBitmap
    return PlatformManager.getBitmapFromRect(self.x, self.y, self.w, self.h)
  File "E:\3rdParty\Python-2.7.12\lib\site-packages\lackey\PlatformManagerWindows.py", line 348, in getBitmapFromRect
    img = self._getVirtualScreenBitmap()
  File "E:\3rdParty\Python-2.7.12\lib\site-packages\lackey\PlatformManagerWindows.py", line 577, in _getVirtualScreenBitmap
    img = self._captureScreen(monitors[monitor_id]["name"])
  File "E:\3rdParty\Python-2.7.12\lib\site-packages\lackey\PlatformManagerWindows.py", line 438, in _captureScreen
    hdc = self._gdi32.CreateDCA(ctypes.c_char_p(device_name), 0, 0, 0)
WindowsError: exception: access violation reading 0x0000000C00000000
`

**Comment by 23233** [comment] 2017-01-11 05:11
## HI~ Please use MarkDown style edit issues

### i don't this  framework Developer i'm try contact @glitchassassin

**Comment by glitchassassin** [comment] 2017-01-11 12:42
This looks like a different issue, @jazz1215. Could you open a new issue to track this in?

Thanks!

**Comment by glitchassassin** [comment] 2017-01-17 16:26
This has been fixed in the latest release.

**Closed by glitchassassin** 2017-01-17 16:26 UTC
Labels: bug, fix in testing
