### ISSUE TITLE
support on mac OS

### ISSUE THREAD

**Issue by wangtubs** [glitchassassin/lackey#78] opened 2017-03-26 19:08 UTC
currently the lackey can't work on mac 
```
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 12:39:47) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lackey
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lackey/__init__.py", line 29, in <module>
    from .PlatformManagerWindows import PlatformManagerWindows
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/lackey/PlatformManagerWindows.py", line 12, in <module>
    from ctypes import wintypes
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/wintypes.py", line 19, in <module>
    class VARIANT_BOOL(_SimpleCData):
ValueError: _type_ 'v' not supported
```

**Comment by glitchassassin** [comment] 2017-03-26 19:12
Correct. I am expecting to have a Macbook to work with in the near future, at which point I'll implement OS X support as quickly as possible!

**Comment by glitchassassin** [comment] 2017-04-10 12:50
Closing issue as duplicate of #56.

**Closed by glitchassassin** 2017-04-10 12:50 UTC
Labels: enhancement
